### ISSUE TITLE
Feature request: CLI interface

### ISSUE THREAD

**Issue by ryami333** [pkgjs/nv#12]
Hi there, I would find it really useful if this package supported CLI use, so that I could do the following:

```zsh
npx @pkgjs/nv lts/erbium
```

**Comment by wesleytodd** [comment]
Hey @ryami333, I completely agree that would be a great feature.  If you opened a PR using `yargs` to do this I am sure we would want to get it merged.

**Comment by helio-frota** [comment]
hi folks I saw this issue, then decided to try to contribute with PR
the cli end up this way: `nv --show=foo` , another example `nv  --show="10.0.0 || ~12.0.0"`
since I not found too much requirement, I decided to send the result to stdout via console.log().
please let me know if that works :+1:

**Comment by shadowspawn** [comment]
For interest, `n` and `nvm` and `nvs` all use the command `ls` for listing their local versions and `ls-remote` for listing the remote downloadable versions.

On Mac and Linux (not Windows) can do:

```
npx n ls-remote erbium
```

**Comment by wesleytodd** [comment]
I started from @helio-frota's work and just added some of the other flags and tweaked things based on the feedback in that PR.  Reviews would be great on #16, going to close this in favor of discussion there.
