### ISSUE TITLE
unused property (tag)

### ISSUE THREAD

**Issue by bnb** [pkgjs/nv#20]
presently, upon outputting all data, it seems that the "tag" property is completely empty. is there any reason to keep it?

**Comment by dominykas** [comment]
Looks like it comes from here:

https://github.com/pkgjs/nv/blob/31c43b903461d305dbf468e9e5001158f91f20be/index.js#L166-L169

I guess Node.js never used that, so it may not be necessary, but maybe that code needs to be replaced with `semver.parse()` anyways, given that `semver` is already a dep, and return the `prerelease` prop, however I'm not sure what was the original use case for `tag` here.

**Comment by wesleytodd** [comment]
The tag (now `prerelease`) is used in canary builds. There is a test which covers this. See #33 for a fix and moving to use `semver`
