### ISSUE TITLE
Include NPM version

### ISSUE THREAD

**Issue by ovflowd** [pkgjs/nv#26]
It'd be great if the Response Object also includes which version of NPM is bundled with each Node.js release.

**Comment by AugustinMauroy** [comment]
+1 it's can be very useful

**Comment by wesleytodd** [comment]
Oh I am wrong! Just checked the code and I think we just need to drop it [in here](https://github.com/pkgjs/nv/blob/main/index.js#L78-L90): 

```
npm: ver.npm
```
